name: Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - run: npm ci

      # Bootstrap
      # TODO(aomarks) Install a known good version for bootstrapping.
      - run: npx tsc

      - run: npm run test:runmode
