name: Tests

on: [push, pull_request, workflow_dispatch]

env:
  # SHOW_OUTPUT: 1
  GITHUB_CACHE: 1
  TEST_TIMEOUT: 120000

jobs:
  tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - run: npm ci

      # Bootstrap
      # TODO(aomarks) Install a known good version for bootstrapping.
      - run: npx tsc

      # TODO(aomarks) Integrate this into our action.
      - name: Expose GitHub variables
        uses: crazy-max/ghaction-github-runtime@v1

      - run: npm test
